/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"IBM Plex Sans"', 'Helvetica Neue', 'Arial', 'sans-serif'],
      },
      colors: {
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-pressed': 'var(--color-primary-pressed)',
        'on-primary': 'var(--color-on-primary)',
        ink: 'var(--color-ink)',
        'ink-muted': 'var(--color-ink-muted)',
        'ink-subtle': 'var(--color-ink-subtle)',
        canvas: 'var(--color-canvas)',
        'surface-1': 'var(--color-surface-1)',
        'surface-2': 'var(--color-surface-2)',
        'inverse-canvas': 'var(--color-inverse-canvas)',
        'inverse-surface-1': 'var(--color-inverse-surface-1)',
        'inverse-ink': 'var(--color-inverse-ink)',
        'inverse-ink-muted': 'var(--color-inverse-ink-muted)',
        hairline: 'var(--color-hairline)',
        'hairline-strong': 'var(--color-hairline-strong)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        error: 'var(--color-error)',
        info: 'var(--color-info)',
      },
      borderColor: {
        DEFAULT: 'var(--color-hairline)',
      },
      borderRadius: {
        none: '0',
        xs: '2px',
        sm: '4px',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '96px',
      },
      fontSize: {
        'display-xl': ['76px', { lineHeight: '1.17', letterSpacing: '-0.5px', fontWeight: '300' }],
        'display-lg': ['60px', { lineHeight: '1.17', letterSpacing: '-0.4px', fontWeight: '300' }],
        'display-md': ['42px', { lineHeight: '1.20', letterSpacing: '0', fontWeight: '300' }],
        headline: ['32px', { lineHeight: '1.25', letterSpacing: '0', fontWeight: '400' }],
        'card-title': ['24px', { lineHeight: '1.33', letterSpacing: '0', fontWeight: '400' }],
        subhead: ['20px', { lineHeight: '1.40', letterSpacing: '0', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.50', letterSpacing: '0', fontWeight: '400' }],
        body: ['16px', { lineHeight: '1.50', letterSpacing: '0.16px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.29', letterSpacing: '0.16px', fontWeight: '400' }],
        'body-emphasis': ['14px', { lineHeight: '1.29', letterSpacing: '0.16px', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '1.33', letterSpacing: '0.32px', fontWeight: '400' }],
        button: ['14px', { lineHeight: '1.29', letterSpacing: '0.16px', fontWeight: '400' }],
        eyebrow: ['14px', { lineHeight: '1.29', letterSpacing: '0.16px', fontWeight: '400' }],
      },
      letterSpacing: {
        carbon: '0.16px',
      },
      transitionDuration: {
        fast: '70ms',
        moderate: '150ms',
      },
      transitionTimingFunction: {
        productive: 'cubic-bezier(0.2, 0, 0.38, 0.9)',
      },
    },
  },
  plugins: [],
};
